correcting requrements file name in workflow

diff --git a/.github/workflows/13-deployFlaskapp.yaml b/.github/workflows/13-deployFlaskapp.yaml
--- a/.github/workflows/13-deployFlaskapp.yaml
+++ b/.github/workflows/13-deployFlaskapp.yaml
@@ -30,7 +30,7 @@ jobs:
             - name: Install Dependencies
               run: |
                 python -m pip install --upgrade pip
-                pip install -r requirments.txt
+                pip install -r requirements.txt
             
             - name: Run unit Tests
               run: |
@@ -45,8 +45,8 @@ jobs:
           - name: Perform Health Check
             run: |
                for i in {1..10}; do 
-                   curl -s -o /dev/null -w "%{http_code}" $Healthcheck_endpoint | grep "200" && echo "Health check Passed .." && exit 0 || echo "waiting for service ..."
+                   curl -s -o /dev/null -w "%{http_code}" $Healthcheck_endpoint | grep "200" && echo "Health check Passed ..." && exit 0 || echo "waiting for service ..."
                    sleep 5
                done;
-               echo "Helath check failed.." && exit 1
+               echo "Health check failed ..." && exit 1
 
